language:     c

sudo:         true

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

env:
  - FLAGS=""
  - FLAGS="-DCML_NO_MATH=ON -DCML_NO_STDBOOL=ON -DCML_NO_STDINT=ON"
  - C_FLAGS=""
  - C_FLAGS="-std=c89"

script:
  - git clone https://github.com/ScientificC/errno.git
  - pushd errno
  - mkdir build && cd build
  - cmake ..
  - make && sudo make install
  - popd
  - mkdir build && cd build
  - cmake --version
  - cmake -trace --warn-uninitialized --warn-unused_vars -Wdev -G "Unix Makefiles" .. -DCML_BUILD_TESTS=ON $FLAGS -DCMAKE_C_FLAGS=$C_FLAGS
  - make && ctest

addons:
  apt:
    packages:
    - cmake
