language: c

sudo: false

os:
  - linux

compiler:
  - gcc
  - clang

script:
  - mkdir build
  - cd build
  - cmake .. -DCML_DOUBLE_PRECISION=ON -Dmfloat_t=double -DCML_BUILD_TESTS=ON
  - make
  - make test
