language:     c

sudo:         false

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

env:
  - FLAGS=""
  - FLAGS="-DCML_LONG_DOUBLE_MATH=ON"
  - FLAGS="-DCML_NO_MATH=ON -DCML_NO_STDBOOL=ON -DCML_NO_STDINT=ON"
  - FLAGS="-DCML_LONG_DOUBLE_MATH=ON -DCML_NO_MATH=ON -DCML_NO_STDBOOL=ON -DCML_NO_STDINT=ON"


script:
  - mkdir build
  - cd build
  - cmake --version
  - cmake -trace --warn-uninitialized --warn-unused_vars -Wdev -G "Unix Makefiles" .. -DCML_BUILD_TESTS=ON $FLAGS
  - make && ctest
  - ./test/test_cml

addons:
  apt:
    packages:
    - cmake
