language:     c

sudo:         false

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

env:
  - FLAGS=""
  - FLAGS="-DCML_NO_MATH=ON -DCML_NO_STDBOOL=ON -DCML_NO_STDINT=ON"
  - C_FLAGS=""
  - C_FLAGS="-ansi"
  - C_FLAGS="-std=c89"

script:
  - mkdir build
  - cd build
  - cmake --version
  - cmake -trace --warn-uninitialized --warn-unused_vars -Wdev -G "Unix Makefiles" .. -DCML_BUILD_TESTS=ON $FLAGS -DCMAKE_C_FLAGS=$C_FLAGS
  - make && ctest
  - echo "Tests for static library"
  - ./test/test_cml_static
  - echo "Tests for shared library"
  - ./test/test_cml_shared

addons:
  apt:
    packages:
    - cmake
