language: c

sudo: false

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

env:
  - FLAGS="-DCML_SINGLE_PRECISION=ON -Dmfloat_t=double"

script:
  - mkdir build
  - cd build
  - cmake --version
  - cmake -trace --warn-uninitialized --warn-unused_vars -Wdev -G "Unix Makefiles" .. -DCML_BUILD_TESTS=ON $FLAGS
  - make && ctest

addons:
  apt:
    packages:
    - cmake
