shallow_clone: true

configuration:
 - Debug
 - Release

environment:
  matrix:
   - vstudio: Visual Studio 14 2015
   - vstudio: Visual Studio 12 2013
   - vstudio: Visual Studio 11 2012
   - vstudio: Visual Studio 10 2010
   - vstudio: Visual Studio 14 2015 Win64
   - vstudio: Visual Studio 12 2013 Win64
   - vstudio: Visual Studio 11 2012 Win64
   - vstudio: Visual Studio 10 2010 Win64

build_script:
 - mkdir build
 - cd build
 - cmake -G "%vstudio%" -trace --warn-uninitialized --warn-unused_vars -Wdev
   --config %configuration%
   -DCMAKE_BUILD_TYPE=%configuration%
   -DCMAKE_INSTALL_PREFIX=../install
   -DCML_BUILD_STATIC=ON
   -DCML_BUILD_SHARED=ON
   ..

test_script:
 - ctest --output-on-failure
   -C %configuration%
